name: TwilioDevOps
on: push
jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: RepoPrep 
        uses: actions/checkout@v2
     
    
  build:
    needs: prep
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [Plugins/plugin-test1, Plugins/plugin-test2]
    steps:
      - name: NodePrep
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm -v
      - name: Building 
        working-directory: ${{ matrix.folder }}
        run: ls -l
