name: TwilioDevOps
on: push
jobs:
  strategy:
    matrix:
      node: [6, 8, 10]
  steps:
    # Configures the node version used on GitHub-hosted runners
    - uses: actions/setup-node@v1
      with:
        # The Node.js version to configure
        node-version: ${{ matrix.node }}
