name: TwilioDevOps

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [Plugins/plugin-test1, Plugins/plugin-test2]
    steps:
      - name: RepoPrep
        uses: actions/checkout@v2

      - name: NodePrep
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Building 
        working-directory: ${{ matrix.folder }}
        run: ls -l
