name: TwilioDevOps
on: push
jobs:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node: [6, 8, 10]
  steps:
    # Configures the node version used on GitHub-hosted runners
      with:
        # The Node.js version to configure
        node-version: ${{ matrix.node }}
