name: Twilio Flex Plugins - PRODUCTION
on: 
  push:
    branches:
      - master
jobs:
  prepare: # Job that list subdirectories inside flex
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name folders by using inner step output
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: echo "::set-output name=dir::$(cd Flex;ls -d */ | sed 's/.$//'| jq -R -s -c 'split("\n")[:-1]')"
        # Define step output named dir base on ls command transformed to JSON using jq.
  buildandrelease:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{fromJson(needs.prepare.outputs.dir)}}
    steps:
      - name: RepositoryPrep
        uses: actions/checkout@v2
      - name: NodeJSPrep
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: GlobalPackages
        run: npm install twilio-cli -g && twilio plugins:install @twilio-labs/plugin-flex 
      - name: Building 
        working-directory: Flex/${{  matrix.folder }} # work within the subdirectory of the plugin
        run: npm install && twilio flex:plugins:test
      - name: DeployingPlugin
        working-directory: Flex/${{  matrix.folder }}
        run: TWILIO_ACCOUNT_SID=${{secrets.DEV_ACCOUNT_SID}} TWILIO_AUTH_TOKEN=${{secrets.DEV_AUTH_TOKEN}} twilio flex:plugins:deploy --changelog "check changelog"
      - name: ReleasingPlugin
        working-directory: Flex/${{  matrix.folder }}
        run: TWILIO_ACCOUNT_SID=${{secrets.DEV_ACCOUNT_SID}} TWILIO_AUTH_TOKEN=${{secrets.DEV_AUTH_TOKEN}} twilio flex:plugins:release --plugin ${{  matrix.folder }}@$(node -p -e "require('./package.json').version")
