name: Twilio Functions - PRODUCTION
on: 
  push:
    branches: 
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: RepositoryPrep
        uses: actions/checkout@v2
      - name: NodeJSPrep
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: twilio plugins:install @twilio-labs/plugin-flex 
      - name: Building 
        working-directory: Functions
        run: npm install twilio-cli -g && twilio plugins:install @twilio-labs/plugin-flex && twilio serverless:deploy --environment=prod --force
  
       
