name: Twilio Functions - PRODUCTION
on: 
  push:
    branches: 
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: RepositoryPrep
        uses: actions/checkout@v2
      - name: NodeJSPrep
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Preparing 
        working-directory: Functions
        run: npm install twilio-cli -g;npm install @twilio-labs/plugin-serverless;twilio plugins:install @twilio-labs/plugin-flex;npm install
      - name: Deploying
        run: twilio serverless:deploy --environment=prod --force

  
       
