name: Twilio Flex Plugins - DEVELOP
on: 
  push:
    branches:
      - develop

jobs:
  prepare: # Job that list subdirectories inside flex

    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name folders by using inner step output
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: |
          echo "::set-output name=dir::$(curl -s  -H "Authorization: token ${{secrets.REPO_TOKEN}}" https://api.github.com/repos/${{github.repository}}/pulls/21/files | jq -r '.[]  .filename' | cut -d "/" -f 1,2 | sed '/^Flex/!d'  | jq -R -s -c 'split("\n")[:-1]')"
        # Define step output named dir base on ls command transformed to JSON using jq.
        # replace the above curl command with the following if you want to run the buildandrelease for every commit
        # cd Flex;ls -d */ | sed 's/.$//'| jq -R -s -c 'split("\n")[:-1]'
      - run: |
          echo "${{steps.set_dirs.outputs.dir}}"
  buildandrelease:
    needs: prepare
    if:  ${{ needs.prepare.outputs.dir != '[]' && needs.prepare.outputs.dir != '' }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{fromJson(needs.prepare.outputs.dir)}}

    steps:
      - name: RepositoryPrep
        uses: actions/checkout@v2
      - name: NodeJSPrep
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: GlobalPackages
        run: npm install twilio-cli -g 
      - run: pwd
      - run: ls
    #  - run: twilio plugins:install @twilio-labs/plugin-flex 
      - name: Preparing 
        working-directory: Flex/${{  matrix.folder }}
        run: npm install
   
