name: TwilioFlexPluginDevOps

on: push

jobs:
  prepare: # Job that list subdirectories
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: echo "::set-output name=dir::$(cd Flex;ls -d */ | sed 's/.$//'| jq -R -s -c 'split("\n")[:-1]')"
        # Define step output named dir base on ls command transformed to JSON thanks to jq.
      - run: git diff-tree --no-commit-id --name-only -r HEAD..origin/master
     
  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{fromJson(needs.prepare.outputs.dir)}}
    steps:
      - name: RepositoryPrep
        uses: actions/checkout@v2
      - name: NodeJSPrep
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: GlobalPackages
        run: npm install twilio-cli -g 
      - run: twilio plugins:install @twilio-labs/plugin-flex 
      - name: Building 
        working-directory: Flex/${{  matrix.folder }}
        run: npm install
    
